## Matrices

<img src="matrix.PNG" width=200>

Matrices are advance versions of atomic vectors with dimensions as a special attribute.

Thus,we can say matrices are special kind of vectors.

Matrices are two dimensional data structures in R. The dimensions are popularly known as rows and columns.

Since they are advance types of atomic vectors, so they can only contain elements of same datatypes.


There are different ways to create a matrix in R.

Let's discuss about them in detail.


In [1]:
#using matrix keyword 

mat = matrix(1:4) #not specifying number of rows and columns

In [2]:
mat

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4

If we do not specify the number of rows and columns while creatinga matrix, by default R assumes the value to be 1 for for columns and 4 for rows and creates a 4*1 matrix.

So you can see the values are filled column wise i.e. all the values are filled in a single column and multiple rows. By default this is how matrix is filled in R.

You can change the default way of filling by using "byrow" keyword.

In [3]:
# let's give rows and columns values

mat = matrix(1:12,nrow=4, ncol = 3)

In [4]:
mat

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

#### change the default filling method

In [5]:
mat = matrix(1:12,nrow=4, ncol = 3,byrow=TRUE)

In [6]:
mat

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

#### you can also give the names of columns and rows in matrix

In [7]:
mat = matrix(1:12,nrow=4, ncol = 3,byrow=TRUE, dimnames = (list(c("row1","row2","row3","row4"),
                                                                c("col1","col2","col3"))))

In [8]:
mat

col1 col2 col3
row1  1    2    3  
row2  4    5    6  
row3  7    8    9  
row4 10   11   12

#### you can get column and row names using function colnames and rownames

In [9]:
rownames(mat)

[1] "row1" "row2" "row3" "row4"

In [10]:
colnames(mat)

[1] "col1" "col2" "col3"

#### you can get dimension of matrix using dim( function)

In [11]:
dim(mat)

[1] 4 3

#### Another method

In [17]:
vec = c(1.2,3.2,4.5,46,54,21)

In [18]:
vec

[1]  1.2  3.2  4.5 46.0 54.0 21.0

In [20]:
# you can call dimension function with dim() function

dim(vec) = c(3,2)

In [21]:
vec

[,1] [,2]
[1,] 1.2  46  
[2,] 3.2  54  
[3,] 4.5  21

In [22]:
# you can add column and row name to this matrix using rownames() and colnames() function

colnames(vec) <- c("A","B")
rownames(vec) <- c("a","b","c")

In [23]:
vec

A   B 
a 1.2 46
b 3.2 54
c 4.5 21

#### Using rbind & cbind to create a matrix

In [24]:
mat3 <- cbind(c(1,2,3,4,5,6)) #creating matrix of one column

In [25]:
mat3

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6

In [26]:
mat3 <- cbind(c(1,2,3),c(12,13,14))

In [27]:
mat3

[,1] [,2]
[1,] 1    12  
[2,] 2    13  
[3,] 3    14

In [28]:
mat4 <- rbind(c(1,2,3,4,5,6)) #matrix of one row

In [29]:
mat4

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    4    5    6

In [30]:
mat4 <- rbind(c(1,2,3),c(4,5,6)) #matrix of one row

In [31]:
mat4

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

#### Accesing elements from Matrix

In [32]:
mat <- matrix(100:115 , nrow =4,ncol = 4 )

In [33]:
mat

[,1] [,2] [,3] [,4]
[1,] 100  104  108  112 
[2,] 101  105  109  113 
[3,] 102  106  110  114 
[4,] 103  107  111  115

In [34]:
colnames(mat) <- c("A","B","C","D")
rownames(mat) <- c(1,2,3,4)

In [35]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [36]:
#access first element

mat[1]

[1] 100

In [37]:
#access 15th element

mat[15]

[1] 114

In [38]:
mat[10]

[1] 109

In [39]:
#access all element of row 3

mat[3,]

A   B   C   D 
102 106 110 114

In [40]:
#access multiple rows

mat[c(2,4),]

A   B   C   D  
2 101 105 109 113
4 103 107 111 115

In [41]:
#access all element of column 

mat[,"A"]

1   2   3   4 
100 101 102 103

In [42]:
#access all element of column 
mat[,1]

1   2   3   4 
100 101 102 103

In [43]:
#access multiple columns

mat[,c("A","B")]

A   B  
1 100 104
2 101 105
3 102 106
4 103 107

In [45]:
mat[,c(1,2)]

A   B  
1 100 104
2 101 105
3 102 106
4 103 107

In [46]:
# access element from a row and column

mat[4,2] #get element from 4throw and 2nd column

[1] 107

In [ ]:
mat[4,][3]

In [ ]:
mat[4,][2] # you can also use this method

In [51]:
mat[1,]["B"]

B 
104

In [52]:
# access specific value in a row or column
mat[1,"C"]

[1] 108

In [53]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [54]:
# accessing multiple rows and columns

mat[c(1,4),c("C","D")]

C   D  
1 108 112
4 111 115

#### Dropping value from matrix

In [56]:
mat[-1,] #prints all rows without 1st row

A   B   C   D  
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [58]:
mat[,-4]  #drops 4th columns

A   B   C  
1 100 104 108
2 101 105 109
3 102 106 110
4 103 107 111

But this does not drop row or column from the matrix actually

In [59]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

If you want to drop values from matrix actually

In [60]:
mat_new <- mat[-1,]

In [61]:
mat_new

A   B   C   D  
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [62]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

#### Accessing elements using logical opeartors

In [63]:
mat[1]

[1] 100

In [64]:
mat[(TRUE)] # mat[c(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,)]

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115

In [65]:
mat[1,]

A   B   C   D 
100 104 108 112

In [66]:
mat[(TRUE),]

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [69]:
mat[c(1,2)]

[1] 100 101

In [70]:
mat[c(TRUE,FALSE)] #get numbers at odd index #recylcing 

[1] 100 102 104 106 108 110 112 114

In [72]:
mat[c(1,2),]

A   B   C   D  
1 100 104 108 112
2 101 105 109 113

In [73]:
mat[c(TRUE,FALSE),] #get numbers at odd index #recylcing 

A   B   C   D  
1 100 104 108 112
3 102 106 110 114

In [74]:
mat[c(FALSE,TRUE)]#get numbers at even index  #recylcing 

[1] 101 103 105 107 109 111 113 115

In [75]:
mat[c(FALSE,TRUE),]

A   B   C   D  
2 101 105 109 113
4 103 107 111 115

In [76]:
mat[c(FALSE,TRUE),c(TRUE,TRUE)]

A   B   C   D  
2 101 105 109 113
4 103 107 111 115

In [ ]:
mat[c(TRUE,FALSE),c(TRUE,FALSE)]

#### Using conditional operators

In [77]:
mat[mat<=109]

[1] 100 101 102 103 104 105 106 107 108 109

In [78]:
mat[mat==105]

[1] 105

#### Modify elements of a Matrix

In [79]:
mat

A   B   C   D  
1 100 104 108 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [80]:
mat[1,][3]

C 
108

In [81]:
mat[1,][3] = 801

In [82]:
mat[1,][3]

C 
801

In [83]:
mat

A   B   C   D  
1 100 104 801 112
2 101 105 109 113
3 102 106 110 114
4 103 107 111 115

In [84]:
mat[,"A"] 

1   2   3   4 
100 101 102 103

In [85]:
mat[,"A"] =c(1,11,12,13)

In [86]:
mat

A  B   C   D  
1  1 104 801 112
2 11 105 109 113
3 12 106 110 114
4 13 107 111 115

In [88]:
class(mat[1])

[1] "numeric"

In [87]:
class(mat[10])

[1] "numeric"

In [89]:
mat[10] ="AB"

In [90]:
mat

A  B   C   D  
1 1  104 801 112
2 11 105 AB  113
3 12 106 110 114
4 13 107 111 115

In [91]:
class(mat[10])

[1] "character"

In [92]:
class(mat[1])

[1] "character"

#### Arithmetic operations on Matrix

In [93]:
mat1 = matrix(1:9, nrow=3,ncol=3)

In [94]:
mat1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [95]:
mat2 = matrix(10:18,nrow=3,ncol=3)

In [96]:
mat2

[,1] [,2] [,3]
[1,] 10   13   16  
[2,] 11   14   17  
[3,] 12   15   18

In [97]:
#sum of matrices
mat1 + mat2 #element wise sum will happen

[,1] [,2] [,3]
[1,] 11   17   23  
[2,] 13   19   25  
[3,] 15   21   27

In [98]:
#element wise matrix multiplication using * operator

mat1 * mat2 

[,1] [,2] [,3]
[1,] 10   52   112 
[2,] 22   70   136 
[3,] 36   90   162

In [99]:
# let try to add matrx of different sizes

mat3 <- matrix(1:6,nrow=3)

In [100]:
mat3

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [101]:
mat1 + mat3

ERROR: Error in mat1 + mat3: non-conformable arrays


In [102]:
mat1 * mat3

ERROR: Error in mat1 * mat3: non-conformable arrays


#### Matrix Multiplication

In [103]:
mat1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [104]:
mat2

[,1] [,2] [,3]
[1,] 10   13   16  
[2,] 11   14   17  
[3,] 12   15   18

In [105]:
mat1 %*% mat2

[,1] [,2] [,3]
[1,] 138  174  210 
[2,] 171  216  261 
[3,] 204  258  312

In [106]:
mat3

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [107]:
#let's try to do matrix multiplication with matrices of different size

 mat3 %*% mat1

ERROR: Error in mat3 %*% mat1: non-conformable arguments


#### Transposing matrix

In [108]:
mat3_transpose = t(mat3)

In [109]:
mat3_transpose

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [110]:
mat3_transpose %*% mat1

[,1] [,2] [,3]
[1,] 14   32    50 
[2,] 32   77   122

## Arrays

Arrays are matrices with more than 2 dimensions i.e. arrays are multi dimensional matrices.

In [111]:
arr = array(1:12,dim=c(2,2,3)) #dimension represents rows,columns and number of matrices

#so we basically are creating 3 matrices of dim 2*2

In [112]:
print(arr)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12



#### Naming Col and Rows

In [114]:
vec1 = c(1,2,3,4)
vec2 = c(7,8,9,10)

colnames = c("A","B")
rownames = c("a","b")

mat_names = c("Mat1","Mat2")

In [115]:
arr_mat = array(c(vec1,vec2),dim = c(2,2,2), dimnames = list(rownames,colnames,mat_names))

In [116]:
print(arr_mat)

, , Mat1

  A B
a 1 3
b 2 4

, , Mat2

  A  B
a 7  9
b 8 10



#### Accessing elements from arrays

In [117]:
arr_mat[1,1,1] #first row first column from first matrix

[1] 1

In [118]:
arr_mat[1,1,2] #first row first column from second matrix

[1] 7

In [119]:
arr_mat[2,,2] #whole second row from second matrix

A  B 
 8 10

In [120]:
arr_mat[,2,1] #whole second columns from first matrix

a b 
3 4

In [121]:
arr_mat[,,1] #all elements of first matrix

A B
a 1 3
b 2 4

In [123]:
arr_mat[1,1,]

Mat1 Mat2 
   1    7